### ISSUE TITLE
Quilt fail to apply patch when the patch file had been dos2unix-ed

### ISSUE THREAD

**Issue by gmc444-b** [yashi/quilt#1]
I'm using quilt to apply patches to third party debian packages. I had a patch file that was working, but when it was checked into my github repo, the carriage returns line terminators were turned into line feeds. When the patch was re-applied to the same original source, it failed with the message "Reversed (or previously applied) patch detected!", which I didn't find very informative. Visually comparing the patch against the source being patched didn't flag anything for me, since the differences were in the invisible whitespace.

In this particular case, the patch was to actually remove a file that contained four lines of text. The correct file looks like this:

```
--- a/poetry-core-1.0.8/poetry/__init__.py
+++ /dev/null
@@ -1,4 +0,0 @@
-from pkgutil import extend_path^M
-^M
-^M
-__path__ = extend_path(__path__, __name__)^M
```

Ideally, I'd hope that the EOL type would not affect the application of a patch, or at least cause quilt to fall back to fuzzy matching and still succeed.

**Comment by yashi** [comment]
Hi @gmc444-b,

This is just a clone of the original repository used to submit pull-request to the upstream.  You should ask to the community directly at https://savannah.nongnu.org/projects/quilt .

BTW, the message is actually from `patch` command Quilt uses.  The project is at https://savannah.gnu.org/projects/patch/

One more thing.  If you have [`core.autocrlf`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf) set, Git will convert your line-ending char. Make sure you have a proper setting.

**Comment by gmc444-b** [comment]
Thanks for the very helpful clarifications, @yashi and my apologies for misfiling this issue. I'll check my settings and I'll look into the savannah projects.
